# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: fr/
    weight: 10
  - name: Publications
    url: /publication
    weight: 14
  - name: Parcours
    url: experience/
    weight: 16
  - name: Projets
    url: projects/
    weight: 12
  - name: Cours
    url: courses/
    weight: 18
